### ISSUE TITLE
# [biocswirl] Complete "neuroinformatics" snRNA-seq Course 

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocSwirl#10]
# [biocswirl] Complete "neuroinformatics" snRNA-seq Course 

About: to be added onto existing scRNA course. 
* Note will be a course going over comparisons

# Tasks 
- [x] Complete course outline
- [x] Draft pipeline(s) that can demonstrate scRNA and snRNAseq differences well

# Resources
This is a good workflow to use: 
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0209648

https://github.com/AllenInstitute/L5_VEN
https://github.com/Sun-lab/scRNAseq_pipelines

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)

**Comment by e-hutchins** [comment]
So far, this course, courses/neuroinformatics, contains:

0) complete lesson highlighting differences between snRNA-Seq and scRNA-seq data
1) a lesson outline for running seurat on both sets of data

Ideas for further development:
 - incorporating PsychEncode deconvolution data, [ Bulk RNA-Seq Decomposition and Deconvolution with Single-cell Data](http://resource.psychencode.org/)

**Comment by e-hutchins** [comment]
P.S. This is the tutorial for the seurat lesson, maybe it can be added to the main scRNA-seq course as well.

[https://scrnaseq-course.cog.sanger.ac.uk/website/seurat-chapter.html](seurat tutorial)
