### ISSUE TITLE
auxillary swirl functions don't work within course environment

### ISSUE THREAD

**Issue by juliaphilipp** [biocswirl-dev-team/BiocSwirl#31]
bye() , play() ,nxt(), and skip() don't work within course.
swirl::bye() works, so it's likely an issue with importing the swirl package properly

**Comment by lisancao** [comment]
This issue has been fixed

**Comment by lisancao** [comment]
Hi @JuliaPhilipp, can you update this issue with the fix you used? Thanks!

**Comment by lisancao** [comment]
For future reference, also see here: https://github.com/biocswirl-dev-team/BiocSwirl/issues/26
