### ISSUE TITLE
RNA-seq fastq download lesson

### ISSUE THREAD

**Issue by neuroendokat** [biocswirl-dev-team/BiocSwirl#33]
Hello,

One of my students is trying to complete this lesson and when she enters "24" for the question about human cell lines in the sample, swirl unexpectedly exits. Any suggestions?

Thanks!

**Comment by juliaphilipp** [comment]
Hi Kat,
thanks for bringing this to our attention!

I'm not quite sure what the reason for this is. I'll keep you posted. In the meantime, your student might want to try to start the course with a different user name, to start with a clean slate. This has helped me get through this question.

**Comment by juliaphilipp** [comment]
Hi Kat,
sorry for the delay. This issue should be resolved. However, for the fix to be effective you'll have to update (uninstall and re-install the RNAseq course). Code for that below:

```
library(BiocSwirl)
uninstall_course('RNAseq')
load_course('RNAseq')
```

after that, you should be able to start the course like you're used to. unfortunately, your progress will be lost.

Let us know if the problem persists.
