### ISSUE TITLE
RNA seq lesson 5

### ISSUE THREAD

**Issue by neuroendokat** [biocswirl-dev-team/BiocSwirl#34]
Hi, one of my students is encountering the following error at the end of lesson 5:

txi <- tximport(salmon.files, txOut=T)
reading in files with read.delim (install 'readr' package for speed up)
1 Error in c(abundanceCol, countsCol, lengthCol) %in% names(raw):
argument "abundanceCol" is missing

**Comment by juliaphilipp** [comment]
Hi Kat,

just to make sure, are you typing `txi <- tximport(salmon.files, type = "salmon", txOut=T)`? The `type = "salmon"` argument might be vital to the function recognizing the type of files that are being read in.

**Comment by lisancao** [comment]
Hi @neuroendokat, are we okay to close this issue? Thanks

**Comment by neuroendokat** [comment]
Yes, sorry for the delay!
